### PR TITLE
show total loan amount payed

### PR DESCRIPTION
**Pull request by mlevin5**
id like to be able to view the total loan amount paid, including interest and inflation, over time. i fear i either coded this incorrectly, or there is a bug in the code, and the numbers aren't matching up how i expect them to when i put interest at 1 and uncheck inflation. lmk !

### CODE REVIEW

**Comment by sportdeath** [comment]
ill take a look although "total amount paid" may be misleading since $1 now will likely be equivalent to 1.02^30 = $1.81 in 30 years. Perhaps "inflation adjusted total amount paid" would be more useful?

**Comment by mlevin5** [comment]
@sportdeath def could be misleading, but for testing purposes, when interest is 1 and inflation is checked off, this should be the same as the principal right? im finding it to be a lot higher

**Comment by sportdeath** [comment]
Interest is measured in percent, so interest needs to be 0%. Although it looks like theres a bug where you get NaN when interest=0. Setting it to 0.00001 seems to work. I'll try to fix the NaN and maybe add a toggle for inflation adjustment.

**Comment by sportdeath** [comment]
Screenshot 2024-05-15 at 6 57 37 PM

looks good to me...

**Comment by mlevin5** [comment]
yay! i am still getting NaN on an edge case but i can try to investigate since its a lil hard to describe how to repro --edit: nvm, just turns out inflation of 2 is too high for the calculation if interest is 0

**Comment by sportdeath** [comment]
I believe it was fixed in https://github.com/horseyhouse/finance-calculator/commit/d7c6ddbd95dcd20714d995b1efce6583fcfbf408

When you check "Inflate with Mortgage Payment" sometimes it requires actually having a negative payment because otherwise its not possible for the sum of mortgage and personal loan to inflate fast enough otherwise.

**Pull request merged**
